openapi: 3.0.0
info:
  title: Data Handin Three
  description: |
    This is a sample Petstore server.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/mathn16/DataHandinThree/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://petstore.swagger.io/v2
paths:
  /postEntry:
    post:
      tags:
      - Entry
      summary: Adds a new entry
      operationId: addEntry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entry'
      responses:
        "200":
          description: ok
        "405":
          description: Invalid input
      x-swagger-router-controller: Entry
  /entry/getEntries:
    get:
      operationId: entryGetEntriesGET
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReturnEntry'
                x-content-type: application/json
        "400":
          description: Invalid status value
      x-swagger-router-controller: Default
  /resetEntries:
    post:
      operationId: resetEntriesPOST
      responses:
        "200":
          description: ok
        "400":
          description: invalid input
      x-swagger-router-controller: Default
components:
  schemas:
    Entry:
      type: object
      properties:
        lumen:
          type: integer
        temp:
          type: integer
        timeStamp:
          type: string
    ReturnEntry:
      type: object
      properties:
        lumen:
          type: integer
        temp:
          type: integer
        timeStamp:
          type: string
        receivedDate:
          type: string
      example:
        timeStamp: timeStamp
        temp: 6
        lumen: 0
        receivedDate: receivedDate
